/*
	날짜 : 2025/08/08
    이름 : 손진일
    내용 : 3장 제약조건 실습
*/

-- 실습 3-1. 기본키 실습하기
create table user2 (
	uid varchar(10) primary key, -- 테이블의 첫 번째 컬럼은 거의 pk
    name varchar(10),
    birth char(10),
    addr varchar(50)
);

-- 실습 3-2. user2 데이터 추가하기
insert into user2 values ('a101', '김유신', '1999-09-19', '김해시');


-- Oracle에서는 byte단위, MySQL에서는 length단위이다. 괄호 () 안에 들어가는 수
-- NUMBER GENERATED BY DEFAULT AS IDENTITY = AUTO_INCREMENT